[package]
name = "key_value_pluggable_storage"
version = "0.1.0"
authors = ["Milan Kub√≠k <email@kubikmilan.sk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
